version: "3.8"
services:
  next:
    container_name: next_tech_dev
    build:
      context: ./next
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./next:/app
    depends_on:
      - express
    networks:
      - frontend
  express:
    container_name: express_tech_dev
    build:
      context: ./express
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    volumes:
      - ./express:/app
    networks:
      - backend
  mongodb:
    container_name: mongodb_tech_dev
    image: mongo:latest
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - backend
  nginx:
    container_name: nginx_tech_dev
    image: nginx:alpine
    depends_on:
      - next
    volumes:
      - ./nginx/development/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - frontend
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
